# This is a basic workflow to help you get started with Actions

name: create release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
#   push:
#     branches: [ develop ]
#   pull_request:
#     branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone --single-branch https://github.com/wireapp/wire-ios-shared-resources.git
          mkdir -p fastlane
          cp wire-ios-shared-resources/Azure/release-framework/Fastfile fastlane/Fastfile
          sudo xcode-select -switch /Applications/Xcode_12.4.app
          
          fastlane build_binary
